;;; Run: emacs --batch -Q -l home/programs/kitty/test_workspace.el
(require 'ert)
(require 'cl-lib)
(defmacro map! (&rest _args) nil)
(load-file (or (getenv "WORKSPACE_EL")
               (expand-file-name "~/.config/doom/config/keybindings/workspaces.el")))
(ert-deftest workspace-project-directory ()
  (let (command)
    (cl-letf (((symbol-function 'projectile-project-root) (lambda () "/tmp/a b;$(literal)/"))
              ((symbol-function 'shell-command) (lambda (cmd) (setq command cmd) 0)))
      (bah/kitty-launch-workspace)
      (should (equal command (concat "kitty @ --to=unix:@mykitty kitten balance_splits.py workspace "
                                     (shell-quote-argument "/tmp/a b;$(literal)/")))))))
(ert-deftest workspace-default-directory ()
  (let ((default-directory "/tmp/") command)
    (cl-letf (((symbol-function 'projectile-project-root) (lambda () nil))
              ((symbol-function 'shell-command) (lambda (cmd) (setq command cmd) 0)))
      (bah/kitty-launch-workspace)
      (should (string-suffix-p " /tmp/" command)))))
(ert-deftest workspace-launch-failure ()
  (cl-letf (((symbol-function 'projectile-project-root) (lambda () "/tmp/"))
            ((symbol-function 'shell-command) (lambda (_) 1)))
    (should-error (bah/kitty-launch-workspace) :type 'user-error)))
(ert-run-tests-batch-and-exit)
