# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  # This needs a seed script to work correctly.
  # So what we need to run _once_ a few seconds into startup:
  # `podman exec -it sh -c "npm run cli db seed -- --swe"`
  virtualisation.oci-containers.containers."logto-app" = {
    image = "svhd/logto:latest";
    environmentFiles = [
      config.clan.core.vars.generators.logto-postgres-login.files."envFile".path
    ];
    environment = {
      "ADMIN_ENDPOINT" = "https://admin-todos.hagenlocher.me";
      "ENDPOINT" = "https://auth-todos.hagenlocher.me";
      "TRUST_PROXY_HEADER" = "1";
    };
    ports = [
      "3001:3001/tcp"
      "3002:3002/tcp"
    ];
    dependsOn = [
      "logto-postgres"
    ];
    log-driver = "journald";
    extraOptions = [
      "--entrypoint=[\"npm\", \"start\"]"
      "--health-cmd=[\"wget\", \"--quiet\", \"--tries=1\", \"--spider\", \"http://localhost:3001/health\"]"
      "--health-start-period=60s"
      "--health-interval=10s"
      "--health-timeout=3s"
      "--health-retries=5"
      "--network-alias=app"
      "--network=logto_default"
    ];
  };
  systemd.services."podman-logto-app" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-logto_default.service"
    ];
    requires = [
      "podman-network-logto_default.service"
    ];
    partOf = [
      "podman-compose-logto-root.target"
    ];
    wantedBy = [
      "podman-compose-logto-root.target"
    ];
  };
  virtualisation.oci-containers.containers."logto-postgres" = {
    image = "postgres:17-alpine";
    environmentFiles = [
      config.clan.core.vars.generators.logto-postgres-login.files."envFile".path
    ];
    environment = {
      "POSTGRES_DB" = "logto";
      "POSTGRES_USER" = "postgres";
    };
    volumes = [
      "logto_postgres_data:/var/lib/postgresql/data:rw"
    ];
    user = "postgres";
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready --username=postgres"
      "--health-interval=10s"
      "--health-retries=5"
      "--health-timeout=5s"
      "--network-alias=postgres"
      "--network=logto_default"
    ];
  };
  systemd.services."podman-logto-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-logto_default.service"
      "podman-volume-logto_postgres_data.service"
    ];
    requires = [
      "podman-network-logto_default.service"
      "podman-volume-logto_postgres_data.service"
    ];
    partOf = [
      "podman-compose-logto-root.target"
    ];
    wantedBy = [
      "podman-compose-logto-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-logto_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f logto_default";
    };
    script = ''
      podman network inspect logto_default || podman network create logto_default
    '';
    partOf = [ "podman-compose-logto-root.target" ];
    wantedBy = [ "podman-compose-logto-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-logto_postgres_data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect logto_postgres_data || podman volume create logto_postgres_data
    '';
    partOf = [ "podman-compose-logto-root.target" ];
    wantedBy = [ "podman-compose-logto-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-logto-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
