# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."logto-app" = {
    image = "svhd/logto:latest";
    environment = {
      "ADMIN_ENDPOINT" = "${admin_endpoint}";
      "DB_URL" = "postgres://postgres:${postgres_password}@postgres:5432/logto";
      "ENDPOINT" = "${endpoint}";
      "TRUST_PROXY_HEADER" = "1";
    };
    ports = [
      "3001:3001/tcp"
      "3002:3002/tcp"
    ];
    dependsOn = [
      "logto-postgres"
    ];
    log-driver = "journald";
    extraOptions = [
      "--entrypoint=[\"npm\", \"start\"]"
      "--health-cmd=[\"wget\", \"--quiet\", \"--tries=1\", \"--spider\", \"http://localhost:3001/api/status\"]"
      "--health-interval=10s"
      "--health-retries=3"
      "--health-timeout=5s"
      "--network-alias=app"
      "--network=logto_default"
    ];
  };
  systemd.services."podman-logto-app" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-logto_default.service"
    ];
    requires = [
      "podman-network-logto_default.service"
    ];
    partOf = [
      "podman-compose-logto-root.target"
    ];
    wantedBy = [
      "podman-compose-logto-root.target"
    ];
  };
  virtualisation.oci-containers.containers."logto-postgres" = {
    image = "postgres:17-alpine";
    environment = {
      "POSTGRES_DB" = "logto";
      "POSTGRES_PASSWORD" = "${postgres_password}";
      "POSTGRES_USER" = "postgres";
    };
    volumes = [
      "logto_postgres_data:/var/lib/postgresql/data:rw"
    ];
    user = "postgres";
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready --username=postgres"
      "--health-interval=10s"
      "--health-retries=5"
      "--health-timeout=5s"
      "--network-alias=postgres"
      "--network=logto_default"
    ];
  };
  systemd.services."podman-logto-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-logto_default.service"
      "podman-volume-logto_postgres_data.service"
    ];
    requires = [
      "podman-network-logto_default.service"
      "podman-volume-logto_postgres_data.service"
    ];
    partOf = [
      "podman-compose-logto-root.target"
    ];
    wantedBy = [
      "podman-compose-logto-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-logto_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f logto_default";
    };
    script = ''
      podman network inspect logto_default || podman network create logto_default
    '';
    partOf = [ "podman-compose-logto-root.target" ];
    wantedBy = [ "podman-compose-logto-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-logto_postgres_data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect logto_postgres_data || podman volume create logto_postgres_data
    '';
    partOf = [ "podman-compose-logto-root.target" ];
    wantedBy = [ "podman-compose-logto-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-logto-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
